spring.application.name=obspot

obspot.security.token.secret=${JWT_SECRET:2P3CmIqXBPWT8JJc0MH7fPwe5uvT8n7b82fSgWaK10vWaW8WkK0YPav2ymCnC+js3SL7HixqUnowc7uv+usEVQ==}
obspot.security.token.expiration=${JWT_EXPIRATION:3600000}

#---
spring.config.activate.on-profile=dev

spring.application.name=obpost-dev

server.port=8082

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.name=${DB_NAME:obspot_dev}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.flyway.enabled=false

spring.docker.compose.file=dev-compose.yaml

#---
spring.config.activate.on-profile=debug

logging.level.br=debug

#---
spring.config.activate.on-profile=info

logging.level.br=info

#---
spring.config.activate.on-profile=prod

spring.application.name=obspot-prod

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none

logging.level.br=info

spring.docker.compose.file=prod-compose.yaml

spring.devtools.add-properties=false

spring.datasource.name=${DB_NAME:obspot_prod}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}

